/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crowdfundingo.inversionista;

import crowdfundingo.controladores.globalvars;
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Henry Ruiz
 */
public class buscaproye extends javax.swing.JFrame {

    /**
     * Creates new form buscaproye
     */
    public buscaproye() {
        initComponents();
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("res/ico.png"));
        return retValue;
    }

    public void llenarTablaProy(String titulo) throws SQLException, ClassNotFoundException {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection(globalvars.conn, "crowdfundingo", "12345");
        con.setSchema("CROWDFUNDINGO");
        Statement s = con.createStatement();
        if (titulo.isEmpty() == false) {
            s.executeQuery("SELECT P.ID, TITULO,PAIS,'$'||DINERO AS DINERO_RECAUDADO,NOMBRES||' '||APELLIDOS AS EMPRENDEDOR FROM USUARIO U, PROYECTO P WHERE U.ID = P.ID_EMP AND P.TITULO='" + titulo + "'");
        } else {
            s.executeQuery("SELECT P.ID, TITULO,PAIS,'$'||DINERO AS DINERO_RECAUDADO,NOMBRES||' '||APELLIDOS AS EMPRENDEDOR FROM USUARIO U, PROYECTO P WHERE U.ID = P.ID_EMP");
        }
        ResultSet rs = s.getResultSet();
        System.out.println(rs);
        ProyTables.setModel(DbUtils.resultSetToTableModel(rs));
    }

    public void llenarTablaProy() throws SQLException, ClassNotFoundException {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection(globalvars.conn, "crowdfundingo", "12345");
        con.setSchema("CROWDFUNDINGO");
        Statement s = con.createStatement();
        s.executeQuery("SELECT P.ID, TITULO,PAIS,'$'||DINERO AS DINERO_RECAUDADO,NOMBRES||' '||APELLIDOS AS EMPRENDEDOR FROM USUARIO U, PROYECTO P WHERE U.ID = P.ID_EMP");
        ResultSet rs = s.getResultSet();
        System.out.println(rs);
        ProyTables.setModel(DbUtils.resultSetToTableModel(rs));
    }

    MostraProy mp = new MostraProy();
    String idvar;

    public void mostrarDatos(String ID) throws SQLException, ClassNotFoundException {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con = DriverManager.getConnection(globalvars.conn, "crowdfundingo", "12345");
        con.setSchema("CROWDFUNDINGO");
        Statement s = con.createStatement();
        String query = "SELECT ID, TITULO, LEMA, DINERO, DESCRIPCION, LINK_IMG FROM PROYECTO WHERE ID=" + ID;
        System.out.println(query);
        s.executeQuery(query);
        ResultSet rs = s.getResultSet();
        while (rs.next()) {
            globalvars.idproy = rs.getString("ID");
            mp.setTitulovar(rs.getString("TITULO"));
            mp.setLemavar(rs.getString("LEMA"));
            mp.setDinerovar(rs.getString("DINERO"));
            mp.setDescripcionvar(rs.getString("DESCRIPCION"));
            mp.setLinkvar(globalvars.destiny + rs.getString("LINK_IMG"));
            idvar = rs.getString("ID");
        }
        System.out.println(rs);
        if (idvar.isEmpty() == false) {
            mp.show();
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblenun = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProyTables = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        proys = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblenun1 = new javax.swing.JLabel();
        id_entr = new javax.swing.JTextField();
        mostraID = new javax.swing.JButton();
        lblenun2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar proyectos");
        setMaximumSize(new java.awt.Dimension(614, 480));
        setMinimumSize(new java.awt.Dimension(614, 480));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblenun.setText("Escriba el Titulo de la campaña:");

        ProyTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITULO ", "LEMA", "PAÍS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProyTables.setColumnSelectionAllowed(true);
        ProyTables.setDoubleBuffered(true);
        ProyTables.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProyTables);
        ProyTables.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (ProyTables.getColumnModel().getColumnCount() > 0) {
            ProyTables.getColumnModel().getColumn(0).setResizable(false);
            ProyTables.getColumnModel().getColumn(1).setResizable(false);
            ProyTables.getColumnModel().getColumn(2).setResizable(false);
            ProyTables.getColumnModel().getColumn(3).setResizable(false);
        }

        buscar.setText("Refrescar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        lblenun1.setText("Escriba el ID de la campaña:");

        mostraID.setText("Mostrar Datos");
        mostraID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraIDActionPerformed(evt);
            }
        });

        lblenun2.setText("No escriba nada en el campo para que se refresque los proyectos creados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblenun)
                                .addGap(10, 10, 10)
                                .addComponent(proys, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblenun1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_entr, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostraID))
                    .addComponent(lblenun2))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(lblenun))
                .addGap(3, 3, 3)
                .addComponent(lblenun2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_entr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblenun1)
                    .addComponent(mostraID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            llenarTablaProy(proys.getText());
        } catch (SQLException ex) {
            Logger.getLogger(buscaproye.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(buscaproye.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void mostraIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraIDActionPerformed
        try {
            mostrarDatos(id_entr.getText());
        } catch (SQLException ex) {
            Logger.getLogger(buscaproye.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "No se encuentra tal proyecto");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(buscaproye.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostraIDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            llenarTablaProy();
        } catch (SQLException ex) {
            Logger.getLogger(buscaproye.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(buscaproye.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscaproye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscaproye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscaproye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscaproye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscaproye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProyTables;
    private javax.swing.JButton buscar;
    public javax.swing.JTextField id_entr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblenun;
    private javax.swing.JLabel lblenun1;
    private javax.swing.JLabel lblenun2;
    private javax.swing.JButton mostraID;
    private javax.swing.JTextField proys;
    // End of variables declaration//GEN-END:variables
}
